---
title: "Homework 1"
author: "Kelly Wang"
date: 2019-09-15
output: github_document
---


```{r setup, include=FALSE}
library(tidyverse)
````

# Problem 1

## creating the data frame
`````{r create dataframe}
## 1.creating a random sample of size 8 from a standard normal distribution
## 2. a logical vector indicating whether elements of the sample are greater than 0
## 3. a character vector of length 8
## 4. a factor vector of length 8, with 3 different factor "levels"
problem1_df=tibble(
  x= rnorm(8),
  vec_logic = x>0,
  vec_char = c("I'm", "a", "fan", "of", "pineapple", "on", "pizza",   "yum!"),
  vec_factor= c("high", "medium", "low", "low", "medium", "high", "medium", "medium")
)
````
##taking mean of each variable in the data frame
```` {r}
#create variable
number=pull(problem1_df, var=x)
overzero=pull(problem1_df, var=vec_logic)
characters=pull(problem1_df, var=vec_char)
levels=pull(problem1_df, var=vec_factor)

#trying to find mean of each variable
mean(number)
mean(overzero)
mean(characters)
mean(levels)

`````
We can take the mean values of number, overzero, but not of characters or levels. 

## using as.numeric function to the logical, character, and factor variables
```{r, eval=FALSE}
as.numeric(overzero)
as.numeric(characters)
as.numeric(levels)

````
This cannot turn into any of the logical, character, or factor vector.

## converting one variable to another
```{r}
#convert the logical vector to numeric, and multiple the random sample by the result
y=number*as.numeric(overzero)
y

#convert the logical vector to a factor, and multiple the random sample by the result
a=number*as.factor(overzero)
a

#convert the logical vector to a factor and then convert the result to numeric, and multiply the random sample by the result
b=number*as.numeric(as.factor(overzero))
b
```` 

